name: Run Subscription Convert

on:
  schedule:
    - cron: '0 */12 * * *' # 每 12 小时运行一次
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run convert script
        run: python convert.py

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # 判断文件是否存在后再进行 git add，防止因未生成文件引发 128 报错
          if [ -f "kv4ynTKhcJWXZ3h.yaml" ]; then
            git add kv4ynTKhcJWXZ3h.yaml kv4ynTKhcJWXZ3h.txt
            git diff-index --quiet HEAD || git commit -m "Auto update subscription files"
            git push
          else
            echo "未找到生成的文件，跳过 Git 提交"
            exit 1
          fi
